name: Minecraft

####################################################################################################
# サービス
####################################################################################################
services:
  server:
    build: .
    image: minecraft/bedrock/alpine
    container_name: bedrock-on-docker
    volumes:
      - ./bedrock_server:/app/bedrock_server
    networks:
      default:
        ipv4_address: 172.16.238.21
    ports:
      - "19132:19132/udp"
    stdin_open: true
    tty: true

####################################################################################################
# ネットワーク : ネットワークスイッチっぽいやつ？
####################################################################################################
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
