name: Minecraft

####################################################################################################
# サービス
####################################################################################################
services:
  server:
    build: .
    image: minecraft/bedrock/alpine
    container_name: bedrock-on-docker
    ports:
      - "19132:19132/udp"
    # これを有効にすると Dockerfile で COPY したファイルを上書きしてしまうため有効にできない
    # volumes:
    #   - ./bedrock_server:/app/bedrock_server
    stdin_open: true
    tty: true
    network_mode: host
